name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build_dir
      run: mkdir build
    
    - name: build1
      run: cd build;cmake ..;make
    
    - name: build2
      run: cd build;cmake ..;make
